Repository curationexperts/tenejo, pull requests merged in 2019-01, with the labels that each got.

#75 Upgrade Hyrax to 2.4.1
  Gemfile
  Gemfile.lock
Labels: review

#94 Add various sample CSV manifests
  spec/fixtures/csv_import/errors/.DS_Store
  spec/fixtures/csv_import/errors/Sample - Connell - duplicate headers.csv
  spec/fixtures/csv_import/errors/Sample - Connell - missing required header.csv
  spec/fixtures/csv_import/errors/not_really_a.csv
  spec/fixtures/csv_import/good/Sample - Connell - minimal.csv
  spec/fixtures/csv_import/warnings/Sample - Connell - extra columns.csv
  spec/fixtures/csv_import/warnings/Sample - Connell - extra fields.csv
  spec/fixtures/csv_import/warnings/Sample - Connell - extraa columns quotes.csv
  spec/fixtures/csv_import/warnings/Sample - Connell - missing required fields.csv
Labels: in progress

#107 Fix array showing up in collection selection
  .rubocop.yml
  app/views/csv_imports/_collection_selection.html.erb
  app/views/csv_imports/preview.html.erb
  app/views/csv_imports/show.html.erb
  spec/system/import_from_csv_spec.rb
Labels: in progress

#127 Converted feature specs to system specs.
  Gemfile
  Gemfile.lock
  spec/rails_helper.rb
  spec/system/create_work_spec.rb
  spec/system/dashboard_spec.rb
  spec/system/import_from_csv_spec.rb
  spec/system/import_from_csv_with_errors_spec.rb
Labels: in progress, review

#130 Install chromedriver-helper
  .travis.yml
  Gemfile
  Gemfile.lock
Labels: in progress, review

#129 Added a GET route for csv import preview page that just redirects to …
  config/routes.rb
Labels: in progress, review
